version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:           # to access the container from outside
      - "8000:8000"
    #env_file: web/venv
    environment:
      DEBUG: 'true'
    command: [ "python", "manage.py runserver 0.0.0.0:8000" ]

  #nginx:
  #  restart: always
  #  build: ./nginx/
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - web-static:/www/static
  #  links:
  #    - web:web

  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'maps_data'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'chicommons'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3406:3406"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
